"""punch init — first-wave bootstrap scanner / readiness mapper.

Non-destructive. Scans a target repo's GitHub Copilot + documentation surface,
proposes a local governance key (Punch = *template origin*, never the active
project identity), maps existing assets onto the Punch lifecycle core, flags
documentation / tracking candidates for later ``/document`` reconciliation, and
records Graphify readiness.

This is a bootstrap SCANNER, not a reconciler. It never renames, deletes, or
rewrites existing files. The real, ongoing documentation reconciliation belongs
to ``/document`` (Punch Document). The artifacts this command emits are clearly
marked as disposable first-wave bootstrap output.

The scanner itself uses only the standard library. YAML is hand-rendered (the one
machine-readable artifact has a fixed shape, so a tiny serializer is enough and
the scanner does not need the orchestrator's pinned PyYAML dependency).
"""

from __future__ import annotations

import argparse
import json
import shutil
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

TEMPLATE_ORIGIN = "Punch"

GENERATED_BANNER = (
    "> **Generated by `punch init`.**\n"
    "> This is a first-wave bootstrap scan, not the canonical documentation "
    "reconciliation.\n"
    "> This file may be deleted or archived after the Punch governance adoption "
    "is complete.\n"
)

# Stable substring of GENERATED_BANNER — used to recognize (and skip) init's own
# disposable output when re-scanning.
_GENERATED_MARKER = "Generated by `punch init`"

# Lifecycle core the scan maps existing assets onto.
LIFECYCLE_CORE = [
    "spec", "plan", "build", "test", "review", "ship", "document",
    "governance-adopt", "docs-reconcile", "ai-assets-audit",
]

# Filename/path tokens → lifecycle phase. Synonyms fold into the core phase.
PHASE_TOKENS = {
    "spec": "spec", "shape": "spec", "understand": "spec", "define": "spec",
    "plan": "plan", "planning": "plan",
    "build": "build", "implement": "build", "slice": "build", "code": "build",
    "test": "test", "verify": "test", "prove": "test", "tdd": "test",
    "review": "review", "audit": "review",
    "ship": "ship", "release": "ship", "deploy": "ship",
    "document": "document", "documentate": "document", "docs": "document",
    "governance": "governance", "governance-audit": "governance",
}

# Documentation-debt / tracking signal tokens (task-supplied list).
DEBT_TOKENS = [
    "plan", "plans", "status", "state", "track", "tracking", "roadmap", "todo",
    "backlog", "feature", "features", "implementation", "migration", "refactor",
    "draft", "notes", "spec", "decision", "adr", "old", "legacy", "archive",
    "copilot", "prompt", "skill", "agent",
]

# Vocabulary mirrors the classify step in .github/prompts/punch-document.prompt.md.
# If that prompt's classify vocabulary changes, update these queries in sync.
GRAPHIFY_QUERIES = [
    "Which markdown files describe implemented features?",
    "Which markdown files describe planned or in-progress features?",
    "Which files look like status, state, plan, roadmap, or tracking documents?",
    "Which documentation files are central to the architecture?",
    "Which prompts, skills, agents, and instructions reference each other?",
    "Which docs appear disconnected from code, tests, prompts, or skills?",
    "Which feature claims have no code or test evidence?",
]


# ----------------------------------------------------------------------------- #
# data
# ----------------------------------------------------------------------------- #
@dataclass
class AssetRecord:
    path: str
    asset_type: str            # instruction | prompt | skill | agent | chatmode | governance doc | unknown
    phase: str                 # spec | plan | ... | governance | unknown
    has_frontmatter: bool
    refs_punch: bool
    refs_local: bool
    refs_graphify: bool
    refs_others: bool
    status: str                # active | duplicate | orphan | ambiguous
    action: str                # keep | adapt | register | review | archive-later | ignore


@dataclass
class DebtCandidate:
    path: str
    reason: str
    likely_type: str
    confidence: str            # low | medium | high
    processor: str             # Punch Document | Feature Ledger | AI Assets Governance | Human Review


@dataclass
class ScanResult:
    identity_key: str
    identity_source: str
    identity_needs_confirmation: bool
    assets: list[AssetRecord]
    doc_groups: dict[str, list[str]]
    debt: list[DebtCandidate]
    graphify: dict
    readiness: dict[str, str]
    overall_status: str
    lifecycle_map: list[dict]
    missing_phases: list[str]
    output_dir_rel: str
    output_dir_reason: str
    notes: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------------- #
# helpers
# ----------------------------------------------------------------------------- #
def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _slug(name: str) -> str:
    out = "".join(c if (c.isalnum() or c in "-_") else "-" for c in name.lower())
    while "--" in out:
        out = out.replace("--", "-")
    return out.strip("-") or "project"


def _has_frontmatter(text: str) -> bool:
    return text.lstrip().startswith("---")


def _tokens(rel_path: str) -> list[str]:
    raw = rel_path.lower().replace("\\", "/")
    raw = raw.replace(".prompt.md", "").replace(".agent.md", "")
    raw = raw.replace(".instructions.md", "").replace(".md", "")
    return [t for t in raw.replace("/", "-").replace(".", "-").split("-") if t]


def _markdown_docs(repo_root: Path) -> list[Path]:
    """Root-level + docs/** markdown, deduped and sorted by path.

    Excludes punch init's own generated artifacts so a re-run is idempotent and
    never scans (or flags as debt) the disposable output of a prior run.
    """
    paths: set[Path] = set(repo_root.glob("*.md"))
    docs_dir = repo_root / "docs"
    if docs_dir.is_dir():
        paths.update(p for p in docs_dir.rglob("*.md") if p.is_file())
    return [p for p in sorted(paths) if _GENERATED_MARKER not in _read(p)[:300]]


def _asset_base(path: Path) -> str:
    """Asset basename without the .prompt/.agent compound suffix (for dup checks)."""
    return path.stem.replace(".prompt", "").replace(".agent", "")


# ----------------------------------------------------------------------------- #
# identity
# ----------------------------------------------------------------------------- #
def resolve_identity(repo_root: Path) -> tuple[str, str, bool]:
    """Resolve a local governance key. Punch stays the template origin."""
    pkg = repo_root / "package.json"
    if pkg.is_file():
        try:
            data = json.loads(_read(pkg) or "{}")
            name = (data.get("name") or "").strip()
            if name:
                return _slug(name.split("/")[-1]), "package.json name", False
        except ValueError:
            pass

    pyproject = repo_root / "pyproject.toml"
    if pyproject.is_file():
        for line in _read(pyproject).splitlines():
            s = line.strip()
            if s.startswith("name") and "=" in s:
                val = s.split("=", 1)[1].strip().strip('"').strip("'")
                if val:
                    return _slug(val), "pyproject.toml name", False

    readme = repo_root / "README.md"
    if readme.is_file():
        for line in _read(readme).splitlines():
            if line.startswith("# "):
                return _slug(line[2:]), "README.md first H1", False

    dirname = repo_root.name
    if dirname:
        return _slug(dirname), "repository directory name", True

    return "target-project", "fallback placeholder", True


# ----------------------------------------------------------------------------- #
# copilot asset scan
# ----------------------------------------------------------------------------- #
def _asset_type(rel_path: str) -> str:
    p = rel_path.replace("\\", "/")
    if p == ".github/copilot-instructions.md":
        return "instruction"
    if p.startswith(".github/instructions/"):
        return "instruction"
    if p.startswith(".github/prompts/"):
        return "prompt"
    if p.startswith(".github/skills/"):
        return "skill"
    if p.startswith(".github/agents/"):
        return "agent"
    if p.startswith(".github/chatmodes/"):
        return "chatmode"
    if p in ("AGENTS.md", "CLAUDE.md"):
        return "governance doc"
    return "unknown"


def _phase_of(rel_path: str) -> str:
    for tok in _tokens(rel_path):
        if tok in PHASE_TOKENS:
            return PHASE_TOKENS[tok]
    return "unknown"


def scan_copilot_assets(repo_root: Path, identity_key: str) -> list[AssetRecord]:
    files: list[Path] = []
    ci = repo_root / ".github" / "copilot-instructions.md"
    if ci.is_file():
        files.append(ci)
    for sub in ("instructions", "prompts", "agents", "chatmodes"):
        d = repo_root / ".github" / sub
        if d.is_dir():
            files.extend(sorted(p for p in d.rglob("*.md") if p.is_file()))
    skills_dir = repo_root / ".github" / "skills"
    if skills_dir.is_dir():
        files.extend(sorted(skills_dir.rglob("SKILL.md")))
    for doc in ("AGENTS.md", "CLAUDE.md"):
        p = repo_root / doc
        if p.is_file():
            files.append(p)

    seen = Counter(_asset_base(f) for f in files)

    records: list[AssetRecord] = []
    for f in files:
        rel = _rel(f)
        text = _read(f)
        low = text.lower()
        atype = _asset_type(rel)
        phase = _phase_of(rel)
        refs_others = any(
            marker in text
            for marker in (".github/prompts/", ".github/skills/", ".github/agents/",
                           ".github/instructions/", "[`punch-")
        )
        is_dup = seen[_asset_base(f)] > 1

        if is_dup:
            status = "duplicate"
        elif phase == "unknown" and atype in ("prompt", "instruction", "unknown"):
            status = "ambiguous"
        elif atype in ("skill", "agent") and not refs_others:
            status = "orphan"
        else:
            status = "active"

        refs_punch = "punch" in low
        action = _recommend_action(atype, phase, status, refs_punch)

        records.append(AssetRecord(
            path=rel,
            asset_type=atype,
            phase=phase,
            has_frontmatter=_has_frontmatter(text),
            refs_punch=refs_punch,
            refs_local=identity_key in low,
            refs_graphify="graphify" in low,
            refs_others=refs_others,
            status=status,
            action=action,
        ))
    return records


def _recommend_action(atype: str, phase: str, status: str, refs_punch: bool) -> str:
    if refs_punch:
        # Already a Punch-shaped asset → adapt to the local governance key.
        return "adapt"
    if status == "duplicate":
        return "review"
    if status == "orphan":
        return "archive-later"
    if status == "ambiguous":
        return "review"
    if atype in ("skill", "agent") or phase != "unknown":
        return "register"
    return "keep"


# ----------------------------------------------------------------------------- #
# documentation surface
# ----------------------------------------------------------------------------- #
DOC_GROUP_ORDER = [
    "canonical docs", "architecture docs", "operational docs", "feature docs",
    "historical plans", "status/state/track docs", "generated docs", "unknown docs",
]


def _doc_group(rel_path: str, text: str) -> str:
    p = rel_path.replace("\\", "/").lower()
    name = p.rsplit("/", 1)[-1]
    if "graphify-out/" in p or "/dist/" in p or "generated by" in text[:400].lower():
        return "generated docs"
    if name in ("readme.md", "claude.md", "agents.md") or p in (
        "docs/architecture.md", "docs/ai-context.md", "docs/ai/operating-model.md",
    ):
        return "canonical docs"
    if "architecture" in p:
        return "architecture docs"
    if any(k in p for k in ("history/", "/old", "legacy", "archive", "roadmap")) or (
        "plan" in name
    ):
        return "historical plans"
    if any(k in name for k in ("status", "state", "track", "todo", "backlog")):
        return "status/state/track docs"
    if "feature" in p or "/specs/" in p:
        return "feature docs"
    if any(k in p for k in ("how-to", "how_to", "runbook", "validation", "workflows/", "ops")):
        return "operational docs"
    return "unknown docs"


def scan_doc_surface(repo_root: Path) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {g: [] for g in DOC_GROUP_ORDER}
    for p in _markdown_docs(repo_root):
        rel = _rel(p)
        groups[_doc_group(rel, _read(p))].append(rel)
    return groups


# ----------------------------------------------------------------------------- #
# documentation-debt candidates (detect only — never decide)
# ----------------------------------------------------------------------------- #
def _processor_for(tokens: set[str]) -> str:
    if tokens & {"copilot", "prompt", "skill", "agent"}:
        return "AI Assets Governance"
    if tokens & {"feature", "features", "implementation"}:
        return "Feature Ledger"
    if tokens & {"old", "legacy", "archive"}:
        return "Human Review"
    return "Punch Document"


def scan_debt_candidates(repo_root: Path) -> list[DebtCandidate]:
    out: list[DebtCandidate] = []
    for p in _markdown_docs(repo_root):
        rel = _rel(p)
        toks = set(_tokens(rel))
        hits = toks & set(DEBT_TOKENS)
        # also peek at headings for a softer signal
        heading_hits: set[str] = set()
        for line in _read(p).splitlines()[:40]:
            if line.startswith("#"):
                for t in DEBT_TOKENS:
                    if t in line.lower():
                        heading_hits.add(t)
        all_hits = hits | heading_hits
        if not all_hits:
            continue
        in_history = "history/" in rel or "archive" in rel or "legacy" in rel
        if len(hits) >= 2 or in_history:
            conf = "high"
        elif hits:
            conf = "medium"
        else:
            conf = "low"
        likely = sorted(all_hits)[0]
        reason = "filename/path tokens: " + ", ".join(sorted(hits)) if hits else \
                 "heading tokens: " + ", ".join(sorted(heading_hits))
        out.append(DebtCandidate(
            path=rel, reason=reason, likely_type=likely, confidence=conf,
            processor=_processor_for(all_hits),
        ))
    return out


# ----------------------------------------------------------------------------- #
# graphify readiness
# ----------------------------------------------------------------------------- #
def graphify_readiness(repo_root: Path, with_graphify: bool) -> dict:
    cli = shutil.which("graphify")
    out_dir = repo_root / "graphify-out"
    graph_json = out_dir / "graph.json"
    report = out_dir / "GRAPH_REPORT.md"
    ignore = repo_root / ".graphifyignore"

    info = {
        "cli_installed": cli is not None,
        "cli_path": cli or "",
        "graphify_out_exists": out_dir.is_dir(),
        "graph_json_exists": graph_json.is_file(),
        "report_exists": report.is_file(),
        "graphifyignore_exists": ignore.is_file(),
        "graph_current": False,
        "checked": with_graphify,
        "suggested_commands": [],
        "suggested_queries": GRAPHIFY_QUERIES,
    }

    if graph_json.is_file():
        newest_src = 0.0
        for sub in ("src", "docs", ".github"):
            d = repo_root / sub
            if d.is_dir():
                for f in d.rglob("*"):
                    if f.is_file():
                        try:
                            newest_src = max(newest_src, f.stat().st_mtime)
                        except OSError:
                            pass
        try:
            info["graph_current"] = graph_json.stat().st_mtime >= newest_src
        except OSError:
            info["graph_current"] = False

    cmds: list[str] = []
    if not cli:
        cmds.append("# Graphify not on PATH — optional. Install later: uv tool install graphifyy")
    if not graph_json.is_file():
        cmds.append("/graphify .            # build the first repo-wide (global) graph")
    elif not info["graph_current"]:
        cmds.append("/graphify . --update   # refresh the stale global graph")
    if not ignore.is_file():
        cmds.append("# consider adding .graphifyignore to scope the graph")
    info["suggested_commands"] = cmds
    return info


# ----------------------------------------------------------------------------- #
# readiness scoring
# ----------------------------------------------------------------------------- #
def _level(count: int, present_at: int, partial_at: int = 1) -> str:
    if count >= present_at:
        return "present"
    if count >= partial_at:
        return "partial"
    return "missing"


def compute_readiness(repo_root: Path, assets: list[AssetRecord], graphify: dict,
                      doc_groups: dict[str, list[str]]) -> tuple[dict[str, str], str, list[str]]:
    prompts = [a for a in assets if a.asset_type == "prompt"]
    skills = [a for a in assets if a.asset_type == "skill"]
    agents = [a for a in assets if a.asset_type == "agent"]
    ci = repo_root / ".github" / "copilot-instructions.md"
    govdocs = [a for a in assets if a.asset_type == "governance doc"]

    if ci.is_file():
        ci_level = "present"
    elif govdocs:
        ci_level = "partial"
    else:
        ci_level = "missing"

    covered = {a.phase for a in prompts if a.phase != "unknown"}
    core = {"spec", "plan", "build", "test", "review", "ship", "document"}
    n_core = len(covered & core)
    lifecycle = "present" if n_core >= 5 else ("partial" if n_core >= 1 else "missing")

    gv_dir = repo_root / "docs" / "ai"
    if (gv_dir / "operating-model.md").is_file():
        gov_level = "present"
    elif gv_dir.is_dir() and any(gv_dir.iterdir()):
        gov_level = "partial"
    else:
        gov_level = "missing"

    if graphify["graph_json_exists"] and graphify["graph_current"]:
        gfx = "present"
    elif graphify["cli_installed"] or graphify["graphify_out_exists"]:
        gfx = "partial"
    else:
        gfx = "missing"

    total_docs = sum(len(v) for v in doc_groups.values())

    # Canon lifecycle output patterns: the golden worked example + blank templates.
    templates_dir = repo_root / "docs" / "ai" / "templates" / "lifecycle"
    golden_readme = repo_root / "docs" / "ai" / "golden-lifecycle" / "README.md"
    n_templates = len(list(templates_dir.glob("*.template.md"))) if templates_dir.is_dir() else 0
    has_golden = golden_readme.is_file()
    if n_templates >= 6 and has_golden:
        templates_level = "present"
    elif n_templates or has_golden:
        templates_level = "partial"
    else:
        templates_level = "missing"

    readiness = {
        "github_copilot_instructions": ci_level,
        "prompts": _level(len(prompts), present_at=3),
        "skills": _level(len(skills), present_at=3),
        "agents": _level(len(agents), present_at=3),
        "graphify": gfx,
        "docs_ai_governance": gov_level,
        "lifecycle_mapping": lifecycle,
        "lifecycle_templates": templates_level,  # golden example + copy-ready templates
        "documentation_surface_known": "partial" if total_docs else "missing",  # first wave is partial by nature
    }

    blocking: list[str] = []
    if ci_level == "missing":
        blocking.append("No .github/copilot-instructions.md — Copilot has no always-on rules.")
    if readiness["prompts"] == "missing" and readiness["agents"] == "missing":
        blocking.append("No prompts and no agents — lifecycle commands have nothing to bind to.")

    has_structure = ci_level != "missing" or readiness["prompts"] != "missing" or readiness["agents"] != "missing"
    adoption = (ci_level == "present") and (readiness["prompts"] != "missing" or readiness["agents"] != "missing")
    document = gfx != "missing" and gov_level != "missing" and total_docs > 0

    if not has_structure:
        overall = "not_ready"
    elif document:
        overall = "document_ready"
    elif adoption:
        overall = "adoption_ready"
    else:
        overall = "bootstrap_ready"

    return readiness, overall, blocking


# ----------------------------------------------------------------------------- #
# lifecycle mapping
# ----------------------------------------------------------------------------- #
def build_lifecycle_map(assets: list[AssetRecord]) -> tuple[list[dict], list[str]]:
    mapping: list[dict] = []
    covered: set[str] = set()
    for a in assets:
        if a.asset_type not in ("prompt", "skill", "agent"):
            continue
        if a.phase == "unknown":
            continue
        # Every PHASE_TOKENS value except "governance" is already a core phase.
        core = "review" if a.phase == "governance" else a.phase
        covered.add(core)
        action = "keep (already Punch-shaped)" if a.refs_punch else \
                 ("register as capability" if a.asset_type == "skill" else
                  "keep and consider wrapper or alias")
        mapping.append({
            "existing": a.path, "lifecycle": f"/{core}", "type": a.asset_type, "action": action,
        })
    missing = [f"/{p}" for p in ["spec", "plan", "build", "test", "review", "ship", "document"]
               if p not in covered]
    return mapping, missing


# ----------------------------------------------------------------------------- #
# output location
# ----------------------------------------------------------------------------- #
def resolve_output_dir(repo_root: Path, override: str | None) -> tuple[Path, str, str]:
    if override:
        d = (repo_root / override).resolve()
        return d, _rel(d), "explicit --output flag"
    if (repo_root / "docs" / "ai" / "governance").is_dir():
        d = repo_root / "docs" / "ai" / "governance" / "init"
        return d, _rel(d), "existing docs/ai/governance/ folder"
    if (repo_root / "docs" / "governance").is_dir():
        d = repo_root / "docs" / "governance" / "init"
        return d, _rel(d), "existing docs/governance/ folder"
    d = repo_root / "docs" / "ai" / "governance" / "init"
    return d, _rel(d), "Punch default (docs/ai/governance/init/)"


# ----------------------------------------------------------------------------- #
# orchestration
# ----------------------------------------------------------------------------- #
def scan(repo_root: Path, with_graphify: bool, output_override: str | None) -> ScanResult:
    key, src, needs_conf = resolve_identity(repo_root)
    assets = scan_copilot_assets(repo_root, key)
    doc_groups = scan_doc_surface(repo_root)
    debt = scan_debt_candidates(repo_root)
    gfx = graphify_readiness(repo_root, with_graphify)
    readiness, overall, blocking = compute_readiness(repo_root, assets, gfx, doc_groups)
    lmap, missing = build_lifecycle_map(assets)
    out_dir, out_rel, out_reason = resolve_output_dir(repo_root, output_override)

    notes = list(blocking)
    if needs_conf:
        notes.append(f"Governance key '{key}' inferred from {src} — confirm with a human.")

    return ScanResult(
        identity_key=key, identity_source=src, identity_needs_confirmation=needs_conf,
        assets=assets, doc_groups=doc_groups, debt=debt, graphify=gfx,
        readiness=readiness, overall_status=overall, lifecycle_map=lmap,
        missing_phases=missing, output_dir_rel=out_rel, output_dir_reason=out_reason,
        notes=notes,
    )


# ----------------------------------------------------------------------------- #
# rendering
# ----------------------------------------------------------------------------- #
def _names(key: str) -> dict[str, str]:
    return {
        "builder": f"{key}-builder",
        "governance_reviewer": f"{key}-governance",
        "document_architect": f"{key}-document-architect",
        "graphify_adapter": f"{key}-graphify-adapter",
    }


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def render_init_wave_scan(r: ScanResult) -> str:
    counts = Counter(a.asset_type for a in r.assets)
    surface = ", ".join(f"{k}: {v}" for k, v in sorted(counts.items())) or "none"
    blocking = "\n".join(f"- ❌ {n}" for n in r.notes if "confirm with a human" not in n) or "- ✅ none"
    nonblock = "\n".join(
        f"- ⚠️ {p} lifecycle phase has no mapped asset" for p in r.missing_phases
    ) or "- ✅ none"

    lines = [
        "# INIT_WAVE_SCAN", "",
        GENERATED_BANNER, "",
        f"_Scan time: {_now()}_", "",
        "## Summary", "",
        f"- **Template origin:** {TEMPLATE_ORIGIN} (origin only — not this repo's identity)",
        f"- **Detected project identity (governance key):** `{r.identity_key}`",
        f"- **Key source:** {r.identity_source}"
        + ("  ⚠️ needs human confirmation" if r.identity_needs_confirmation else ""),
        f"- **Existing AI / Copilot surface:** {surface}",
        f"- **Documentation files seen:** {sum(len(v) for v in r.doc_groups.values())}",
        f"- **Doc/tracking reconciliation candidates:** {len(r.debt)}",
        f"- **Output location:** `{r.output_dir_rel}/` ({r.output_dir_reason})",
        "",
        "## Readiness score", "",
        "| Category | Level |", "|---|---|",
    ]
    for k, v in r.readiness.items():
        mark = {"present": "✅", "partial": "⚠️", "missing": "❌"}[v]
        lines.append(f"| {k} | {mark} {v} |")
    lines += [
        "",
        f"**Overall status: `{r.overall_status}`**", "",
        "## Blocking issues", "", blocking, "",
        "## Non-blocking recommendations", "", nonblock, "",
        "## Suggested next command", "",
        "```bash",
        "./bin/punch init --write      # persist these bootstrap maps",
        "# then, once adopted:",
        "/document                     # real documentation reconciliation (Punch Document)",
        "```", "",
        "See `next-actions.md` for the full adoption path.", "",
    ]
    return "\n".join(lines) + "\n"


def render_copilot_assets_map(r: ScanResult) -> str:
    lines = [
        "# copilot-assets-map", "", GENERATED_BANNER, "",
        "First-wave inventory of GitHub Copilot assets. **No files were modified.**",
        "This is a bootstrap proposal — promote into "
        "`docs/ai/governance/ai-assets-registry.md` via `/document` or a governance "
        "adoption step; it is **not** canonical yet.", "",
        "## Inventory", "",
        "| Path | Type | Phase | FM | →Punch? | Graphify? | Status | Action |",
        "|---|---|---|---|---|---|---|---|",
    ]
    if not r.assets:
        lines.append("| _(none detected)_ | | | | | | | |")
    for a in sorted(r.assets, key=lambda x: (x.asset_type, x.path)):
        lines.append(
            f"| `{a.path}` | {a.asset_type} | {a.phase} | "
            f"{'yes' if a.has_frontmatter else 'no'} | "
            f"{'yes' if a.refs_punch else 'no'} | "
            f"{'yes' if a.refs_graphify else 'no'} | {a.status} | {a.action} |"
        )

    lines += ["", "## Suggested lifecycle mapping", "",
              "| Existing | Lifecycle | Type | Action |", "|---|---|---|---|"]
    if not r.lifecycle_map:
        lines.append("| _(no phase-tagged assets)_ | | | |")
    for m in r.lifecycle_map:
        lines.append(f"| `{m['existing']}` | `{m['lifecycle']}` | {m['type']} | {m['action']} |")

    missing = "\n".join(f"- `{p}`" for p in r.missing_phases) or "- ✅ all core phases mapped"
    dups = [a for a in r.assets if a.status == "duplicate"]
    review = [a for a in r.assets if a.action == "review"]
    lines += [
        "", "## Missing lifecycle assets", "", missing,
        "", "## Conflicting / duplicate assets", "",
        ("\n".join(f"- `{a.path}`" for a in dups) or "- ✅ none detected"),
        "", "## Review before adoption", "",
        ("\n".join(f"- `{a.path}` — {a.status}" for a in review) or "- ✅ none flagged"),
        "",
    ]
    return "\n".join(lines) + "\n"


def _yaml_list(items: list[str], indent: str) -> str:
    if not items:
        return f"{indent}[]"
    return "\n".join(f"{indent}- {i}" for i in items)


def render_governance_adoption_map(r: ScanResult) -> str:
    names = _names(r.identity_key)
    cmds = r.graphify["suggested_commands"]
    lines = [
        "# Generated by punch init — first-wave bootstrap scan, not canonical.",
        "# This file may be deleted or archived after Punch governance adoption.",
        "",
        "generated_by: punch init",
        f"generated_at: {_now()}",
        f"template_origin: {TEMPLATE_ORIGIN}",
        "",
        f"governance_key: {r.identity_key}",
        f"governance_key_source: {r.identity_source!r}",
        f"governance_key_needs_confirmation: {str(r.identity_needs_confirmation).lower()}",
        "",
        "# Punch is the template origin; these are the proposed LOCAL persona names.",
        "proposed_local_names:",
        f"  builder: {names['builder']}",
        f"  governance_reviewer: {names['governance_reviewer']}",
        f"  document_architect: {names['document_architect']}",
        f"  graphify_adapter: {names['graphify_adapter']}",
        "",
        "readiness:",
    ]
    for k, v in r.readiness.items():
        lines.append(f"  {k}: {v}")
    lines += [
        "",
        "lifecycle_readiness:",
    ]
    covered = {m["lifecycle"].lstrip("/") for m in r.lifecycle_map}
    for p in ["spec", "plan", "build", "test", "review", "ship", "document"]:
        lines.append(f"  {p}: {'present' if p in covered else 'missing'}")
    lines += [
        "",
        "graphify:",
        f"  cli_installed: {str(r.graphify['cli_installed']).lower()}",
        f"  graphify_out_exists: {str(r.graphify['graphify_out_exists']).lower()}",
        f"  graph_current: {str(r.graphify['graph_current']).lower()}",
        "",
        "overall:",
        f"  status: {r.overall_status}",
        "",
        "suggested_next_graphify_commands:",
        _yaml_list(cmds, "  "),
        "",
    ]
    return "\n".join(lines) + "\n"


def render_documentation_surface_map(r: ScanResult) -> str:
    lines = ["# documentation-surface-map", "", GENERATED_BANNER, "",
             "First-wave grouping of documentation-like files. **Not reconciled** — "
             "candidates are marked for future `/document` processing.", "",
             "> **Dual-classification note:** `AGENTS.md`, `CLAUDE.md`, and `README.md` "
             "are listed here as *canonical docs* and also appear in "
             "`copilot-assets-map.md` as *governance docs* — they serve both roles. "
             "A future `/document` wave should reconcile each once, not twice.", ""]
    for g in DOC_GROUP_ORDER:
        files = r.doc_groups.get(g, [])
        lines.append(f"## {g} ({len(files)})")
        lines.append("")
        if files:
            lines.extend(f"- `{f}`" for f in files)
        else:
            lines.append("- _(none)_")
        lines.append("")

    lines += ["## Reconciliation candidates (detect-only)", "",
              "Future processor per candidate — `/document` decides final status, not init.", "",
              "| Path | Reason | Likely type | Confidence | Future processor |",
              "|---|---|---|---|---|"]
    if not r.debt:
        lines.append("| _(none detected)_ | | | | |")
    for d in sorted(r.debt, key=lambda x: (-{"high": 2, "medium": 1, "low": 0}[x.confidence], x.path)):
        lines.append(f"| `{d.path}` | {d.reason} | {d.likely_type} | {d.confidence} | {d.processor} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_graphify_readiness(r: ScanResult) -> str:
    g = r.graphify
    def b(x): return "✅ yes" if x else "❌ no"
    lines = [
        "# graphify-readiness", "", GENERATED_BANNER, "",
        "Graphify is **optional** — `punch init` never fails when it is absent.", "",
        f"_Availability check requested via `--with-graphify`: "
        f"{'yes' if g['checked'] else 'no (file-readiness is still recorded below)'}._",
        "",
        "`punch init` records Graphify **file-readiness** (the paths below) on every "
        "run and **never shells out** to the `graphify` CLI — that keeps init "
        "dependency-free and Docker-First. `--with-graphify` is an explicit opt-in "
        "marker for this lightweight check; building or refreshing an actual graph is "
        "`/graphify` (see Suggested commands).",
        "",
        "## Status", "",
        f"- CLI installed: {b(g['cli_installed'])}" + (f" (`{g['cli_path']}`)" if g['cli_path'] else ""),
        f"- `graphify-out/` exists: {b(g['graphify_out_exists'])}",
        f"- `graph.json` exists: {b(g['graph_json_exists'])}",
        f"- `GRAPH_REPORT.md` exists: {b(g['report_exists'])}",
        f"- `.graphifyignore` exists: {b(g['graphifyignore_exists'])}",
        f"- Graph appears current: {b(g['graph_current'])}",
        "",
        "## Suggested commands", "", "```bash",
    ]
    lines.extend(g["suggested_commands"] or ["# graph looks current — no action needed"])
    lines += ["```", "", "## Suggested queries for Punch Document", ""]
    lines.extend(f"- {q}" for q in g["suggested_queries"])
    lines.append("")
    return "\n".join(lines) + "\n"


def render_next_actions(r: ScanResult) -> str:
    key = r.identity_key
    lines = [
        "# next-actions", "", GENERATED_BANNER, "",
        f"Adoption path for **`{key}`** (Punch is the template origin).", "",
        "## 1. Finish governance adoption", "",
        f"- Confirm the governance key `{key}`"
        + (" (⚠️ inferred — needs human sign-off)." if r.identity_needs_confirmation else "."),
        "- Decide local persona names (see `governance-adoption-map.yaml`).",
        "- For each Punch-shaped asset marked `adapt`, rebind `punch-*` references to "
        f"the local `{key}-*` identity (do this through `/document`, not by hand here).",
        "",
        "## 2. Enable / adapt lifecycle assets", "",
        "- Prompts/agents/skills marked `keep`/`register` are ready to use.",
        "- Assets marked `review` or `duplicate` need a human look before adoption.",
        ("- Missing lifecycle phases: " + ", ".join(f"`{p}`" for p in r.missing_phases)
         if r.missing_phases else "- ✅ all core lifecycle phases are covered."),
        ("- Lifecycle output patterns (`lifecycle_templates`): "
         f"**{r.readiness.get('lifecycle_templates', 'missing')}**. Adopt the canon "
         "from `docs/ai/templates/lifecycle/`; worked example in "
         "`docs/ai/golden-lifecycle/`."),
        "",
        "## 3. Run Graphify (optional, recommended)", "",
        "- See `graphify-readiness.md`. Build the global repo graph, then keep it "
        "updated between waves.",
        "",
        "## 4. Run Punch Document (the real reconciliation)", "",
        "- `/document` (or `./bin/punch` Document flow) does the ongoing work this "
        "scan only *prepared*: feature ledger, documentation debt, historical-plan "
        "cleanup, lean rewrites.",
        f"- Promote the bootstrap proposals here into canonical registries when ready:",
        "  - `copilot-assets-map.md` → `docs/ai/governance/ai-assets-registry.md`",
        "  - `documentation-surface-map.md` → `docs/ai/governance/docs-inventory.md` "
        "+ `feature-ledger.md` + `documentation-debt.md`",
        "",
        "## 5. Review documentation debt", "",
        f"- {len(r.debt)} candidate(s) flagged in `documentation-surface-map.md`. "
        "Route each to its noted processor (Punch Document / Feature Ledger / "
        "AI Assets Governance / Human Review).",
        "",
        "## 6. Clean up", "",
        "- These init artifacts are disposable. Archive or delete "
        f"`{r.output_dir_rel}/` once adoption is complete.",
        "",
    ]
    return "\n".join(lines) + "\n"


ARTIFACTS = {
    "INIT_WAVE_SCAN.md": render_init_wave_scan,
    "copilot-assets-map.md": render_copilot_assets_map,
    "governance-adoption-map.yaml": render_governance_adoption_map,
    "documentation-surface-map.md": render_documentation_surface_map,
    "graphify-readiness.md": render_graphify_readiness,
    "next-actions.md": render_next_actions,
}


# ----------------------------------------------------------------------------- #
# command entry
# ----------------------------------------------------------------------------- #
def run(args: argparse.Namespace) -> int:
    repo_root = REPO_ROOT
    if not (repo_root / ".git").exists() and not (repo_root / ".github").exists():
        print("[punch init] error: does not look like a repository root "
              "(no .git or .github).", flush=True)
        return 2

    try:
        result = scan(repo_root, with_graphify=args.with_graphify,
                      output_override=args.output)
    except Exception as e:  # robust: a scan crash is a command error, not a readiness fail
        print(f"[punch init] error during scan: {e}", flush=True)
        return 2

    write = bool(args.write) and not args.dry_run

    print(f"[punch init] template origin : {TEMPLATE_ORIGIN}")
    print(f"[punch init] governance key  : {result.identity_key} "
          f"({result.identity_source})"
          + ("  [needs confirmation]" if result.identity_needs_confirmation else ""))
    print(f"[punch init] overall status  : {result.overall_status}")
    print(f"[punch init] copilot assets  : {len(result.assets)} | "
          f"doc files: {sum(len(v) for v in result.doc_groups.values())} | "
          f"debt candidates: {len(result.debt)} | "
          f"graphify: {'installed' if result.graphify['cli_installed'] else 'absent (optional)'}")
    print(f"[punch init] output location : {result.output_dir_rel}/ "
          f"({result.output_dir_reason})")

    rendered = {name: fn(result) for name, fn in ARTIFACTS.items()}

    if write:
        out_dir = repo_root / result.output_dir_rel
        out_dir.mkdir(parents=True, exist_ok=True)
        for name, content in rendered.items():
            (out_dir / name).write_text(content, encoding="utf-8")
            print(f"[punch init] wrote {result.output_dir_rel}/{name}")
    else:
        print("[punch init] DRY-RUN — no files written. Would generate:")
        for name in rendered:
            print(f"             {result.output_dir_rel}/{name}")
        print("[punch init] re-run with --write to persist these bootstrap maps.")

    if result.overall_status == "not_ready":
        print("[punch init] blocking readiness issues found (exit 1):")
        for n in result.notes:
            print(f"             - {n}")
        return 1
    return 0
